
ACTION OvlVentilovychTerminalov: 

		//Mapovanie ventilového terminálu - VT8//
	P4_Pracovisko.OUT.VT8_OUT1.0:= P4_FunkcnyTestA.OUT.ZasunStoper_YV163;
	P4_Pracovisko.OUT.VT8_OUT1.1:= P4_FunkcnyTestB.OUT.ZasunStoper_YV164;
	P4_Pracovisko.OUT.VT8_OUT1.2:= P4_Etiketovacka.OUT.ZasunStoper_YV165;
	P4_Pracovisko.OUT.VT8_OUT1.3:= P4_FunkcnyTestA.OUT.KontaktyTestera_VYSUN_YV171;
	P4_Pracovisko.OUT.VT8_OUT1.4:= P4_FunkcnyTestB.OUT.KontaktyTestera_VYSUN_YV172;
	P4_Pracovisko.OUT.VT8_OUT1.5:= P4_Etiketovacka.OUT.OfukEtikety_ZAPNI_YV174;
	P4_Pracovisko.OUT.VT8_OUT1.6:= P4_Etiketovacka.OUT.Aplikator_VYSUN_YV173;
	P4_Pracovisko.OUT.VT8_OUT1.7; 
	
	P4_Pracovisko.OUT.VT8_OUT2.0:= P4_Etiketovacka.OUT.Prisavanie_ZAPNI_YV175;
	P4_Pracovisko.OUT.VT8_OUT2.1:= P4_Etiketovacka.OUT.Prisavanie_VYPNI_YV176;
	P4_Pracovisko.OUT.VT8_OUT2.2;
	P4_Pracovisko.OUT.VT8_OUT2.3;
	P4_Pracovisko.OUT.VT8_OUT2.4:= P4_Etiketovacka.OUT.VysunCentrovanie_YV166;
	P4_Pracovisko.OUT.VT8_OUT2.5:= P4_Etiketovacka.OUT.ZasunCentrovanie_YV167;
	P4_Pracovisko.OUT.VT8_OUT2.6;
	P4_Pracovisko.OUT.VT8_OUT2.7;
	
	P4_Pracovisko.OUT.VT8_OUT3.0:= P4_FunkcnyTestA.OUT.HorneKontakty_ZASUN_YV177;
	P4_Pracovisko.OUT.VT8_OUT3.1:= P4_FunkcnyTestA.OUT.HorneKontakty_VYSUN_YV178;
	P4_Pracovisko.OUT.VT8_OUT3.2:= P4_FunkcnyTestA.OUT.OdpruzenieKontaktov_ZAPNI_YV179;
	P4_Pracovisko.OUT.VT8_OUT3.3:= P4_FunkcnyTestA.OUT.OdpruzenieKontaktov_VYPNI_YV180;
	P4_Pracovisko.OUT.VT8_OUT3.4:= P4_FunkcnyTestA.OUT.VysunCentrovanie_YV183;
	P4_Pracovisko.OUT.VT8_OUT3.5:= P4_FunkcnyTestA.OUT.ZasunCentrovanie_YV184;
	P4_Pracovisko.OUT.VT8_OUT3.6:= P4_FunkcnyTestA.OUT.SpodneKontakty_ZASUN_YV181;  
	P4_Pracovisko.OUT.VT8_OUT3.7:= P4_FunkcnyTestA.OUT.SpodneKontakty_VYSUN_YV182;
	
	P4_Pracovisko.OUT.VT8_OUT4.0:= P4_FunkcnyTestB.OUT.HorneKontakty_ZASUN_YV185;
	P4_Pracovisko.OUT.VT8_OUT4.1:= P4_FunkcnyTestB.OUT.HorneKontakty_VYSUN_YV186;
	P4_Pracovisko.OUT.VT8_OUT4.2:= P4_FunkcnyTestB.OUT.OdpruzenieKontaktov_ZAPNI_YV187;
	P4_Pracovisko.OUT.VT8_OUT4.3:= P4_FunkcnyTestB.OUT.OdpruzenieKontaktov_VYPNI_YV188;
	P4_Pracovisko.OUT.VT8_OUT4.4:= P4_FunkcnyTestB.OUT.VysunCentrovanie_YV191;
	P4_Pracovisko.OUT.VT8_OUT4.5:= P4_FunkcnyTestB.OUT.ZasunCentrovanie_YV192; 
	P4_Pracovisko.OUT.VT8_OUT4.6:= P4_FunkcnyTestB.OUT.SpodneKontakty_ZASUN_YV189; 
	P4_Pracovisko.OUT.VT8_OUT4.7:= P4_FunkcnyTestB.OUT.SpodneKontakty_VYSUN_YV190; 
	
		
	
	
	
	
END_ACTION
