
ACTION OvlVentilovychTerminalov: 

		//Mapovanie ventilového terminálu - VT4//
	P1_Pracovisko.OUT.VT4_OUT1.0:= P1_AkumulacnyStoper.OUT.ZasunStoper_YV74;
	P1_Pracovisko.OUT.VT4_OUT1.1:= P1_StoperSrobovania.OUT.ZasunStoper_YV110;
	P1_Pracovisko.OUT.VT4_OUT1.2:= P1_SpodnyStoper.OUT.ZasunStoper_YV111;
	P1_Pracovisko.OUT.VT4_OUT1.3:= P1_Srobovanie.OUT.ZasobSrobM4_Ofuk_RUN_YV72;
	P1_Pracovisko.OUT.VT4_OUT1.4:= P1_Srobovanie.OUT.NastrelSrobM4_NastrelSrobu_YV78;
	P1_Pracovisko.OUT.VT4_OUT1.5:= P1_Srobovanie.OUT.ZasobSrobM4_OfukTried_RUN_YV73;
	P1_Pracovisko.OUT.VT4_OUT1.6:= P1_Srobovanie.OUT.NastrelSrobM4_PosunSrobu_YV77;
	P1_Pracovisko.OUT.VT4_OUT1.7; 
	
	P1_Pracovisko.OUT.VT4_OUT2.0:= P1_Srobovanie.OUT.SkrutkM4_PrisavSkrutky_RUN_YV81;
	P1_Pracovisko.OUT.VT4_OUT2.1:= P1_Srobovanie.OUT.SkrutkM4_OfukVakua_RUN_YV80;
	P1_Pracovisko.OUT.VT4_OUT2.2:= P1_Srobovanie.OUT.SkrutkM4_Cist_OTVOR_YV82;
	P1_Pracovisko.OUT.VT4_OUT2.3;
	P1_Pracovisko.OUT.VT4_OUT2.4:= P1_Srobovanie.OUT.SkrutkM4_Cist_POSUN_YV83;
	P1_Pracovisko.OUT.VT4_OUT2.5:= P1_Srobovanie.OUT.SkrutkM4_Cist_ODSAVANIE_YV84;
	P1_Pracovisko.OUT.VT4_OUT2.6:= P1_Srobovanie.OUT.ZasobSrobK30_Ofuk_RUN_YV85;
	P1_Pracovisko.OUT.VT4_OUT2.7:= P1_Srobovanie.OUT.ZasobSrobK30_OfukTried_RUN_YV86;
	
	P1_Pracovisko.OUT.VT4_OUT3.0:= P1_Srobovanie.OUT.NastrelSrobK30_PosunSrobu_YV87;
	P1_Pracovisko.OUT.VT4_OUT3.1;
	P1_Pracovisko.OUT.VT4_OUT3.2:= P1_Srobovanie.OUT.NastrelSrobK30_NastrelSrobu_YV88;
	P1_Pracovisko.OUT.VT4_OUT3.3:= P1_Srobovanie.OUT.SkrutkK30_PrisavSkrutky_RUN_YV90;
	P1_Pracovisko.OUT.VT4_OUT3.4:= P1_Srobovanie.OUT.SkrutkK30_OfukVakua_RUN_YV91;
	P1_Pracovisko.OUT.VT4_OUT3.5;
	P1_Pracovisko.OUT.VT4_OUT3.6:= P1_Srobovanie.OUT.SkrutkK30_Cist_OTVOR_YV92;  
	P1_Pracovisko.OUT.VT4_OUT3.7;
	
	P1_Pracovisko.OUT.VT4_OUT4.0:= P1_Srobovanie.OUT.SkrutkK30_Cist_POSUN_YV123;
	P1_Pracovisko.OUT.VT4_OUT4.1:= P1_Srobovanie.OUT.SkrutkK30_Cist_ODSAVANIE_YV93;
	P1_Pracovisko.OUT.VT4_OUT4.2:= P1_Srobovanie.OUT.ZasobSrobM5_Ofuk_RUN_YV94;
	P1_Pracovisko.OUT.VT4_OUT4.3:= P1_Srobovanie.OUT.ZasobSrobM5_OfukTried_RUN_YV95;
	P1_Pracovisko.OUT.VT4_OUT4.4:= P1_Srobovanie.OUT.OddelovacSrobM5_OtocVZAD_YV102;
	P1_Pracovisko.OUT.VT4_OUT4.5:= P1_Srobovanie.OUT.OddelovacSrobM5_OtocVPRED_YV103; 
	P1_Pracovisko.OUT.VT4_OUT4.6; 
	P1_Pracovisko.OUT.VT4_OUT4.7; 
	
	
	//Mapovanie ventilového terminálu - VT5//
	P1_Pracovisko.OUT.VT5_OUT1.0:= P1_Srobovanie.OUT.SkrutkM4_VYSUN_YV79;
	P1_Pracovisko.OUT.VT5_OUT1.1;
	P1_Pracovisko.OUT.VT5_OUT1.2:= P1_Srobovanie.OUT.SkrutkK30_VYSUN_YV89; 
	P1_Pracovisko.OUT.VT5_OUT1.3;
	P1_Pracovisko.OUT.VT5_OUT1.4:= P1_Srobovanie.OUT.SkrutkM5_VYSUN_YV104; 
	P1_Pracovisko.OUT.VT5_OUT1.5;
	P1_Pracovisko.OUT.VT5_OUT1.6:= P1_StoperSrobovania.OUT.VysunCentrovanie_YV112; 
	P1_Pracovisko.OUT.VT5_OUT1.7:= P1_StoperSrobovania.OUT.ZasunCentrovanie_YV113;
	
	P1_Pracovisko.OUT.VT5_OUT2.0:= P1_Robot.OUT.OdistiGriper_YV107;
	P1_Pracovisko.OUT.VT5_OUT2.1:= P1_Robot.OUT.ZaistiGriper_YV106;
	P1_Pracovisko.OUT.VT5_OUT2.2:= P1_Robot.OUT.OtvorGriper_YV97;
	P1_Pracovisko.OUT.VT5_OUT2.3:= P1_Robot.OUT.ZatvorGriper_YV98;
	P1_Pracovisko.OUT.VT5_OUT2.4:= P1_Robot.OUT.VypniVakum_YV114;
	P1_Pracovisko.OUT.VT5_OUT2.5:= P1_Robot.OUT.ZapniVakum_YV108;
	P1_Pracovisko.OUT.VT5_OUT2.6:= P1_Srobovanie.OUT.SkrutkM5_PrisavSkrut_ZAPNI_YV105; 
	P1_Pracovisko.OUT.VT5_OUT2.7:= P1_Srobovanie.OUT.SkrutkM5_PrisavSkrut_VYPNI_YV109;
		
	P1_Pracovisko.OUT.VT5_OUT3.0;
	P1_Pracovisko.OUT.VT5_OUT3.1;
	P1_Pracovisko.OUT.VT5_OUT3.2;  
	P1_Pracovisko.OUT.VT5_OUT3.3; 
	P1_Pracovisko.OUT.VT5_OUT3.4; 
	P1_Pracovisko.OUT.VT5_OUT3.5;
	P1_Pracovisko.OUT.VT5_OUT3.6; 
	P1_Pracovisko.OUT.VT5_OUT3.7;
	
	P1_Pracovisko.OUT.VT5_OUT4.0;  
	P1_Pracovisko.OUT.VT5_OUT4.1; 
	P1_Pracovisko.OUT.VT5_OUT4.2; 
	P1_Pracovisko.OUT.VT5_OUT4.3; 
	P1_Pracovisko.OUT.VT5_OUT4.4; 
	P1_Pracovisko.OUT.VT5_OUT4.5; 
	P1_Pracovisko.OUT.VT5_OUT4.6; 
	P1_Pracovisko.OUT.VT5_OUT4.7; 
	
	
	
	
	
	
END_ACTION
