
ACTION OvlVentilovychTerminalov: 

		//Mapovanie ventilového terminálu - VT6//
	P3_Pracovisko.OUT.VT6_OUT1.0:= P3_StoperSrobovania.OUT.ZasunStoper_YV132;
	P3_Pracovisko.OUT.VT6_OUT1.1:= P3_AkumulacnyStoper.OUT.ZasunStoper_YV133;
	P3_Pracovisko.OUT.VT6_OUT1.2:= P3_LeakageTestA.OUT.ZasunStoper_YV134;
	P3_Pracovisko.OUT.VT6_OUT1.3:= P3_LeakageTestB.OUT.ZasunStoper_YV135;
	P3_Pracovisko.OUT.VT6_OUT1.4:= P3_SpodnyStoper.OUT.ZasunStoper_YV136;
	P3_Pracovisko.OUT.VT6_OUT1.5:= P3_Srobovanie.OUT.ZasobSrobK40_Ofuk_RUN_YV114;
	P3_Pracovisko.OUT.VT6_OUT1.6:= P3_Srobovanie.OUT.NastrelSrobK40_NastrelSrob_YV117;
	P3_Pracovisko.OUT.VT6_OUT1.7:= P3_Srobovanie.OUT.ZasobSrobK40_OfukTried_RUN_YV115; 
	
	P3_Pracovisko.OUT.VT6_OUT2.0:= P3_Srobovanie.OUT.NastrelSrobK40_PosunSrobu_YV116;
	P3_Pracovisko.OUT.VT6_OUT2.1;
	P3_Pracovisko.OUT.VT6_OUT2.2:= P3_Srobovanie.OUT.SkrutkK40_PrisavSkrut_RUN_YV120;
	P3_Pracovisko.OUT.VT6_OUT2.3:= P3_Srobovanie.OUT.SkrutkK40_OfukVakua_RUN_YV119;
	P3_Pracovisko.OUT.VT6_OUT2.4:= P3_Srobovanie.OUT.SkrutkK40_Cist_OTVOR_YV121;
	P3_Pracovisko.OUT.VT6_OUT2.5;
	P3_Pracovisko.OUT.VT6_OUT2.6:= P3_Srobovanie.OUT.SkrutkK40_Cist_POSUN_YV124;
	P3_Pracovisko.OUT.VT6_OUT2.7:= P3_Srobovanie.OUT.SkrutkK40_Cist_ODSAVANIE_YV122;
	
	P3_Pracovisko.OUT.VT6_OUT3.0:= P3_Srobovanie.OUT.ZasobSrobM5_Ofuk_RUN_YV125;
	P3_Pracovisko.OUT.VT6_OUT3.1:= P3_Srobovanie.OUT.ZasobSrobM5_OfukTried_RUN_YV126;
	P3_Pracovisko.OUT.VT6_OUT3.2:= P3_Srobovanie.OUT.OddelovacSrobM5_OtocVZAD_YV127;
	P3_Pracovisko.OUT.VT6_OUT3.3:= P3_Srobovanie.OUT.OddelovacSrobM5_OtocVPRED_YV128;
	P3_Pracovisko.OUT.VT6_OUT3.4:= P3_Srobovanie.OUT.HVTest_PritlacKontTestera_YV140;
	P3_Pracovisko.OUT.VT6_OUT3.5:= P3_VstupnyStoper.OUT.ZasunStoper_YV193;
	P3_Pracovisko.OUT.VT6_OUT3.6:= P3_Srobovanie.OUT.SkrutkM5_PrisavSkrut_ZAPNI_YV130;  
	P3_Pracovisko.OUT.VT6_OUT3.7:= P3_Srobovanie.OUT.SkrutkM5_PrisavSkrut_VYPNI_YV131;
	
	P3_Pracovisko.OUT.VT6_OUT4.0;
	P3_Pracovisko.OUT.VT6_OUT4.1;
	P3_Pracovisko.OUT.VT6_OUT4.2;
	P3_Pracovisko.OUT.VT6_OUT4.3;
	P3_Pracovisko.OUT.VT6_OUT4.4;
	P3_Pracovisko.OUT.VT6_OUT4.5; 
	P3_Pracovisko.OUT.VT6_OUT4.6; 
	P3_Pracovisko.OUT.VT6_OUT4.7; 
	
	
	//Mapovanie ventilového terminálu - VT7//
	P3_Pracovisko.OUT.VT7_OUT1.0:= P3_Srobovanie.OUT.SkrutkK40_VYSUN_YV118;
	P3_Pracovisko.OUT.VT7_OUT1.1;
	P3_Pracovisko.OUT.VT7_OUT1.2:= P3_Srobovanie.OUT.SkrutkM5_VYSUN_YV129; 
	P3_Pracovisko.OUT.VT7_OUT1.3;
	P3_Pracovisko.OUT.VT7_OUT1.4:= P3_StoperSrobovania.OUT.VysunCentrovanie_YV151; 
	P3_Pracovisko.OUT.VT7_OUT1.5:= P3_StoperSrobovania.OUT.ZasunCentrovanie_YV152;
	P3_Pracovisko.OUT.VT7_OUT1.6:= P3_Srobovanie.OUT.HVTest_Kontakty_VYSUN_YV154; 
	P3_Pracovisko.OUT.VT7_OUT1.7:= P3_Srobovanie.OUT.HVTest_Kontakty_ZASUN_YV153;
	
	P3_Pracovisko.OUT.VT7_OUT2.0:= P3_Srobovanie.OUT.HVTest_VYSUN_YV150;
	P3_Pracovisko.OUT.VT7_OUT2.1:= P3_Srobovanie.OUT.HVTest_ZASUN_YV149;
	P3_Pracovisko.OUT.VT7_OUT2.2:= P3_Srobovanie.OUT.HVTest_PneuPruzinu_VYSUN_YV156;
	P3_Pracovisko.OUT.VT7_OUT2.3:= P3_Srobovanie.OUT.HVTest_PneuPruzinu_ZASUN_YV155;
	P3_Pracovisko.OUT.VT7_OUT2.4:= P3_LeakageTestA.OUT.VysunCentrovanie_YV143;
	P3_Pracovisko.OUT.VT7_OUT2.5:= P3_LeakageTestA.OUT.ZasunCentrovanie_YV144;
	P3_Pracovisko.OUT.VT7_OUT2.6:= P3_LeakageTestA.OUT.Kopito_VYSUN_YV141; 
	P3_Pracovisko.OUT.VT7_OUT2.7:= P3_LeakageTestA.OUT.Kopito_ZASUN_YV142;
		
	P3_Pracovisko.OUT.VT7_OUT3.0:= P3_LeakageTestB.OUT.VysunCentrovanie_YV147;
	P3_Pracovisko.OUT.VT7_OUT3.1:= P3_LeakageTestB.OUT.ZasunCentrovanie_YV148;
	P3_Pracovisko.OUT.VT7_OUT3.2:= P3_LeakageTestB.OUT.Kopito_VYSUN_YV145;  
	P3_Pracovisko.OUT.VT7_OUT3.3:= P3_LeakageTestB.OUT.Kopito_ZASUN_YV146; 
	P3_Pracovisko.OUT.VT7_OUT3.4:= P3_LeakageTestA.OUT.Pritlak_VYSUN_YV157; 
	P3_Pracovisko.OUT.VT7_OUT3.5:= P3_LeakageTestA.OUT.Pritlak_ZASUN_YV158;
	P3_Pracovisko.OUT.VT7_OUT3.6:= P3_LeakageTestA.OUT.PneuZamok_ODOMKNI_YV159; 
	P3_Pracovisko.OUT.VT7_OUT3.7;
	
	P3_Pracovisko.OUT.VT7_OUT4.0:= P3_LeakageTestB.OUT.Pritlak_VYSUN_YV161;  
	P3_Pracovisko.OUT.VT7_OUT4.1:= P3_LeakageTestB.OUT.Pritlak_ZASUN_YV162; 
	P3_Pracovisko.OUT.VT7_OUT4.2:= P3_LeakageTestB.OUT.PneuZamok_ODOMKNI_YV160; 
	P3_Pracovisko.OUT.VT7_OUT4.3; 
	P3_Pracovisko.OUT.VT7_OUT4.4; 
	P3_Pracovisko.OUT.VT7_OUT4.5; 
	P3_Pracovisko.OUT.VT7_OUT4.6; 
	P3_Pracovisko.OUT.VT7_OUT4.7; 
	
	
	
	
	
	
END_ACTION
