
ACTION OvlVentilovychTerminalov: 

	
	//Mapovanie ventilového terminálu - VT1//
	P2_Pracovisko.OUT.VT1_OUT1.0:= P2_StoperZaklTesnenia.OUT.ZasunStoper_YV53;
	P2_Pracovisko.OUT.VT1_OUT1.1:= P2_StoperMaticovacky.OUT.ZasunStoper_YV52;
	P2_Pracovisko.OUT.VT1_OUT1.2;
	P2_Pracovisko.OUT.VT1_OUT1.3:= P2_SkrutkovacMatic.OUT.ZasobMatic_Ofuk_RUN_YV63;
	P2_Pracovisko.OUT.VT1_OUT1.4:= P2_SkrutkovacMatic.OUT.ZasobMatic_OfukTried_RUN_YV64;
	P2_Pracovisko.OUT.VT1_OUT1.5:= P2_SkrutkovacMatic.OUT.OddelMatic_NastrelMaticu_YV65;
	P2_Pracovisko.OUT.VT1_OUT1.6;
	P2_Pracovisko.OUT.VT1_OUT1.7; 
	
	P2_Pracovisko.OUT.VT1_OUT2.0:= P2_SkrutkovacMatic.OUT.SkrutkMatic_PrisavMatic_RUN_YV67;
	P2_Pracovisko.OUT.VT1_OUT2.1:= P2_SkrutkovacMatic.OUT.SkrutkMatic_OfukVakua_RUN_YV66;
	P2_Pracovisko.OUT.VT1_OUT2.2:= P2_SkrutkovacMatic.OUT.PosuvacMatic_PosunMaticu_YV68;
	P2_Pracovisko.OUT.VT1_OUT2.3;
	P2_Pracovisko.OUT.VT1_OUT2.4:= P2_SkrutkovacMatic.OUT.OddelMatic_PosunMaticu_YV69;
	P2_Pracovisko.OUT.VT1_OUT2.5;
	P2_Pracovisko.OUT.VT1_OUT2.6:= P2_Srobovanie.OUT.ZasobSrobM6_Ofuk_RUN_YV30;
	P2_Pracovisko.OUT.VT1_OUT2.7:= P2_Srobovanie.OUT.ZasobSrobM6_OfukTried_RUN_YV31;
	
	P2_Pracovisko.OUT.VT1_OUT3.0:= P2_Srobovanie.OUT.NastrelSrobM6_PosunSrobu_YV32;
	P2_Pracovisko.OUT.VT1_OUT3.1;
	P2_Pracovisko.OUT.VT1_OUT3.2:= P2_Srobovanie.OUT.NastrelSrobM6_NastrelSrobu_YV33;
	P2_Pracovisko.OUT.VT1_OUT3.3:= P2_Srobovanie.OUT.SkrutkM6_PrisavSkrutky_RUN_YV36; 
	P2_Pracovisko.OUT.VT1_OUT3.4;
	P2_Pracovisko.OUT.VT1_OUT3.5:= P2_Srobovanie.OUT.SkrutkM6_OfukVakua_RUN_YV35;
	P2_Pracovisko.OUT.VT1_OUT3.6:= P2_Srobovanie.OUT.SkrutkM6_Cist_OTVOR_YV37; 
	P2_Pracovisko.OUT.VT1_OUT3.7;
	
	P2_Pracovisko.OUT.VT1_OUT4.0:= P2_Srobovanie.OUT.SkrutkM6_Cist_Vakum_RUN_YV39;
	P2_Pracovisko.OUT.VT1_OUT4.1:= P2_Srobovanie.OUT.SkrutkM6_Cist_OfukVakua_RUN_YV38;
	P2_Pracovisko.OUT.VT1_OUT4.2:= P2_StoperSrobovania.OUT.ZasunStoper_YV56;
	P2_Pracovisko.OUT.VT1_OUT4.3:= P2_StoperZvarania.OUT.ZasunStoper_YV59;
	P2_Pracovisko.OUT.VT1_OUT4.4;
	P2_Pracovisko.OUT.VT1_OUT4.5; 
	P2_Pracovisko.OUT.VT1_OUT4.6; 
	P2_Pracovisko.OUT.VT1_OUT4.7; 
	
	
	//Mapovanie ventilového terminálu - VT2//
	P2_Pracovisko.OUT.VT2_OUT1.0:= P2_Cistenie.OUT.VzduchPreIonizator_RUN_YV51;
	P2_Pracovisko.OUT.VT2_OUT1.1:= P2_Cistenie.OUT.Odsavanie_OfukRUN_YV50;
	P2_Pracovisko.OUT.VT2_OUT1.2:= P2_Cistenie.OUT.Odsavanie_RUN_YV49;
	P2_Pracovisko.OUT.VT2_OUT1.3:= P2_Srobovanie.OUT.ZasobSrobM4_Ofuk_RUN_YV20;
	P2_Pracovisko.OUT.VT2_OUT1.4:= P2_Srobovanie.OUT.ZasobSrobM4_OfukTried_RUN_YV21;
	P2_Pracovisko.OUT.VT2_OUT1.5:= P2_Srobovanie.OUT.NastrelSrobM4_NastrelSrobu_YV23;
	P2_Pracovisko.OUT.VT2_OUT1.6:= P2_Srobovanie.OUT.NastrelSrobM4_PosunSrobu_YV22;
	P2_Pracovisko.OUT.VT2_OUT1.7;
	
	P2_Pracovisko.OUT.VT2_OUT2.0:= P2_Srobovanie.OUT.SkrutkM4_PrisavSkrutky_RUN_YV26; 
	P2_Pracovisko.OUT.VT2_OUT2.1:= P2_Srobovanie.OUT.SkrutkM4_OfukVakua_RUN_YV25;
	P2_Pracovisko.OUT.VT2_OUT2.2:= P2_Srobovanie.OUT.SkrutkM4_Cist_OTVOR_YV27;
	P2_Pracovisko.OUT.VT2_OUT2.3;
	P2_Pracovisko.OUT.VT2_OUT2.4:= P2_Srobovanie.OUT.SkrutkM4_Cist_OfukVakua_RUN_YV28; 
	P2_Pracovisko.OUT.VT2_OUT2.5:= P2_Srobovanie.OUT.SkrutkM4_Cist_Vakum_RUN_YV29;
	P2_Pracovisko.OUT.VT2_OUT2.6:= P2_Srobovanie.OUT.ZasobSrobM5_Ofuk_RUN_YV10;
	P2_Pracovisko.OUT.VT2_OUT2.7:= P2_Srobovanie.OUT.ZasobSrobM5_OfukTried_RUN_YV11;
		
	P2_Pracovisko.OUT.VT2_OUT3.0:= P2_Srobovanie.OUT.NastrelSrobM5_PosunSrobu_YV12;
	P2_Pracovisko.OUT.VT2_OUT3.1;
	P2_Pracovisko.OUT.VT2_OUT3.2:= P2_Srobovanie.OUT.NastrelSrobM5_NastrelSrobu_YV13; 
	P2_Pracovisko.OUT.VT2_OUT3.3:= P2_Srobovanie.OUT.SkrutkM5_PrisavSkrutky_RUN_YV16;
	P2_Pracovisko.OUT.VT2_OUT3.4:= P2_Srobovanie.OUT.SkrutkM5_OfukVakua_RUN_YV15;
	P2_Pracovisko.OUT.VT2_OUT3.5;
	P2_Pracovisko.OUT.VT2_OUT3.6:= P2_Srobovanie.OUT.SkrutkM5_Cist_OTVOR_YV19; 
	P2_Pracovisko.OUT.VT2_OUT3.7;
	
	P2_Pracovisko.OUT.VT2_OUT4.0:= P2_Srobovanie.OUT.SkrutkM5_Cist_OfukVakua_RUN_YV17; 
	P2_Pracovisko.OUT.VT2_OUT4.1:= P2_Srobovanie.OUT.SkrutkM5_Cist_Vakum_RUN_YV18;
	P2_Pracovisko.OUT.VT2_OUT4.2:= P2_Robot.OUT.OdistiGriper_YV2;
	P2_Pracovisko.OUT.VT2_OUT4.3:= P2_Robot.OUT.ZaistiGriper_YV1;
	P2_Pracovisko.OUT.VT2_OUT4.4:= P2_Robot.OUT.VypniVakum4F5F_YV7;
	P2_Pracovisko.OUT.VT2_OUT4.5:= P2_Robot.OUT.ZapniVakum4F5F_YV6;
	P2_Pracovisko.OUT.VT2_OUT4.6:= P2_Robot.OUT.VypniVakum5H_YV9;
	P2_Pracovisko.OUT.VT2_OUT4.7:= P2_Robot.OUT.ZapniVakum5H_YV8;
	
	//Mapovanie ventilového terminálu - VT3//
	P2_Pracovisko.OUT.VT3_OUT1.0:= P2_Zvaranie.OUT.PojazdZvarania_VLAVO_YV46;
	P2_Pracovisko.OUT.VT3_OUT1.1:= P2_Zvaranie.OUT.PojazdZvarania_VPRAVO_YV45;
	P2_Pracovisko.OUT.VT3_OUT1.2:= P2_Cistenie.OUT.Dvere_OTVOR_YV47;
	P2_Pracovisko.OUT.VT3_OUT1.3:= P2_Cistenie.OUT.Dvere_ZATVOR_YV48;
	P2_Pracovisko.OUT.VT3_OUT1.4:= P2_StoperMaticovacky.OUT.VysunCentrovanie_YV54;
	P2_Pracovisko.OUT.VT3_OUT1.5:= P2_StoperMaticovacky.OUT.ZasunCentrovanie_YV55;
	P2_Pracovisko.OUT.VT3_OUT1.6:= P2_StoperSrobovania.OUT.VysunCentrovanie_YV57;
	P2_Pracovisko.OUT.VT3_OUT1.7:= P2_StoperSrobovania.OUT.ZasunCentrovanie_YV58;
	
	P2_Pracovisko.OUT.VT3_OUT2.0:= P2_StoperZvarania.OUT.VysunCentrovanie_YV60;
	P2_Pracovisko.OUT.VT3_OUT2.1:= P2_StoperZvarania.OUT.ZasunCentrovanie_YV61;
	P2_Pracovisko.OUT.VT3_OUT2.2:= P2_Robot.OUT.ZatvorGriper_YV4;
	P2_Pracovisko.OUT.VT3_OUT2.3:= P2_Robot.OUT.OtvorGriper_YV3;
	P2_Pracovisko.OUT.VT3_OUT2.4;
	P2_Pracovisko.OUT.VT3_OUT2.5;
	P2_Pracovisko.OUT.VT3_OUT2.6;
	P2_Pracovisko.OUT.VT3_OUT2.7;
	
	P2_Pracovisko.OUT.VT3_OUT3.0:= P2_Srobovanie.OUT.SkrutkM6_VYSUN_YV34;
	P2_Pracovisko.OUT.VT3_OUT3.1;
	P2_Pracovisko.OUT.VT3_OUT3.2:= P2_Srobovanie.OUT.SkrutkM4_VYSUN_YV24;
	P2_Pracovisko.OUT.VT3_OUT3.3;
	P2_Pracovisko.OUT.VT3_OUT3.4:= P2_Srobovanie.OUT.SkrutkM5_VYSUN_YV14;
	P2_Pracovisko.OUT.VT3_OUT3.5;
	P2_Pracovisko.OUT.VT3_OUT3.6;
	P2_Pracovisko.OUT.VT3_OUT3.7;
	
	P2_Pracovisko.OUT.VT3_OUT4.0;
	P2_Pracovisko.OUT.VT3_OUT4.1;
	P2_Pracovisko.OUT.VT3_OUT4.2;
	P2_Pracovisko.OUT.VT3_OUT4.3;
	P2_Pracovisko.OUT.VT3_OUT4.4;
	P2_Pracovisko.OUT.VT3_OUT4.5;
	P2_Pracovisko.OUT.VT3_OUT4.6;
	P2_Pracovisko.OUT.VT3_OUT4.7;
	
	
	
	
	
END_ACTION
